#!/bin/bash
# Learning Review Prompt - Background self-learning automation
#
# Checks for accumulated session learnings and creates a reminder
# to review them via /dex-whats-new --learnings
#
# Designed to run daily at 5pm via macOS Launch Agent
# Creates a prompt file that session-start.sh will detect

VAULT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SESSION_LEARNINGS_DIR="$VAULT_ROOT/System/Session_Learnings"
PROMPT_FILE="$VAULT_ROOT/System/learning-review-pending.md"
LOG_DIR="$VAULT_ROOT/.scripts/logs"
LOG_FILE="$LOG_DIR/learning-review.log"

# Create log directory if needed
mkdir -p "$LOG_DIR"

# Logging function
log() {
  echo "[$(date -u +"%Y-%m-%dT%H:%M:%SZ")] $1" | tee -a "$LOG_FILE"
}

log "=== Learning Review Check Started ==="

# Check if Session_Learnings directory exists
if [[ ! -d "$SESSION_LEARNINGS_DIR" ]]; then
  log "Session_Learnings directory not found, skipping"
  exit 0
fi

# Count pending learnings (files from last 7 days with "pending" status)
PENDING_COUNT=0
WEEK_AGO=$(date -v-7d +%Y-%m-%d)

log "Scanning for learnings since $WEEK_AGO"

# Find learning files from the past week
for file in "$SESSION_LEARNINGS_DIR"/*.md; do
  if [[ ! -f "$file" ]]; then
    continue
  fi
  
  # Extract date from filename (YYYY-MM-DD.md)
  filename=$(basename "$file" .md)
  
  # Skip README
  if [[ "$filename" == "README" ]]; then
    continue
  fi
  
  # Check if file is from the past week
  if [[ "$filename" > "$WEEK_AGO" ]] || [[ "$filename" == "$WEEK_AGO" ]]; then
    # Count "pending" learnings in this file
    pending=$(grep -c "^\*\*Status:\*\* pending" "$file" 2>/dev/null || echo "0")
    # Strip any whitespace and ensure it's a number
    pending=$(echo "$pending" | tr -d '[:space:]')
    pending=${pending:-0}
    PENDING_COUNT=$((PENDING_COUNT + pending))
  fi
done

log "Found $PENDING_COUNT pending learnings"

# If 5+ pending learnings, create prompt file
if [[ $PENDING_COUNT -ge 5 ]]; then
  log "Creating learning review prompt (threshold met: $PENDING_COUNT >= 5)"
  
  cat > "$PROMPT_FILE" <<EOF
# 📚 Pending Learnings Review

**Count:** $PENDING_COUNT pending learnings from the past week
**Detected:** $(date -u +"%Y-%m-%d %H:%M UTC")

---

## What to Do

You have accumulated learnings from recent sessions that haven't been reviewed yet.

Run \`/dex-whats-new --learnings\` to:
- Review patterns identified from your usage
- See suggested system improvements
- Mark learnings as implemented or archived

This helps sw_os evolve based on your actual workflow patterns.

---

*Auto-generated by .scripts/learning-review-prompt.sh*
EOF

  log "Prompt file created at $PROMPT_FILE"
else
  log "Threshold not met ($PENDING_COUNT < 5), no prompt needed"
  
  # Remove any existing prompt file
  if [[ -f "$PROMPT_FILE" ]]; then
    rm "$PROMPT_FILE"
    log "Removed existing prompt file"
  fi
fi

log "=== Learning Review Check Complete ==="
